name: composite-actions
inputs:
  nodeVersion:
    description: Version of Nodejs
    type: string
    required: true
    default: 18.x
runs:
    using: "composite"

    steps:
        - name: Setup NodeJs
          uses: actions/setup-node@4.0.2
          with:
            node-version: 18.x



